### ISSUE TITLE
Another Suggestion

### ISSUE THREAD

**Issue by Foxiseminger** [hiimjustin000/FakeRate#10]
Make it so you can rate the level, and also not have it have stars. So Like fake rate is currently like this:

        Auto
EXTREME DEMON
        10⭐

but can you make it like

         Auto
EXTREME DEMON
      No Stars

**Comment by heavyutils** [comment]
Was just about to post that

**Comment by NexusSfan** [comment]
Maybe you can pick any amount of stars from 1-10 instead of just no stars or difficulty star.

**Comment by hiimjustin000** [comment]
Added in v1.2.0
