### ISSUE TITLE
It trips out in gauntlets

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#14]
Idk how to explain it just looks real weird ratings and gems show up weirdly you can try it for yourself

**Comment by hiimjustin000** [comment]
Show me

**Comment by heavyutils** [comment]
> Show me

I didn't manage to get a screenshot but the issue is actually pretty simple. The stars shown  in the gauntlet view is not the ones set with Fake Rate, and the gem count appears 2 places

**Comment by hiimjustin000** [comment]
Node IDs issue probably

**Comment by hiimjustin000** [comment]
Which platform is this happening on?

**Comment by heavyutils** [comment]
Windows

**Comment by hiimjustin000** [comment]
You mentioned you didn't manage to get a screenshot. Are you able to get one now?

**Comment by heavyutils** [comment]
It seems to be fixed.
