### ISSUE TITLE
Selection the Harder difficulty sometimes crashes the game

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#16]
When doing the fake rate sometimes the second you click on "Harder" face the game crashes

**Comment by hiimjustin000** [comment]
On where? DIfficulty selection?

**Comment by hiimjustin000** [comment]
Also, send the crashlog

**Comment by heavyutils** [comment]
Yes on the difficulty selection. Geode didn't generate a new crashlog and it didn't even say Crashed or anything when i reopened the game. It was some windows error thingy or smth but your mod was referenced in it.

**Comment by hiimjustin000** [comment]
I can't reproduce this issue. What level did you try to rate as Harder?

**Comment by heavyutils** [comment]
"dorabaebasic7" was what failed. I had previously rated it Hard 5* in gd 2.204.

**Comment by heavyutils** [comment]
Ok it crashed again but with a log this time
[2024-06-27_20-28-17.log](https://github.com/user-attachments/files/16019420/2024-06-27_20-28-17.log)

**Comment by heavyutils** [comment]
boom, now it deleted all my fake rates... :(

**Comment by hiimjustin000** [comment]
I'm sorry to hear that.

I'll get to fixing.

**Comment by hiimjustin000** [comment]
This was caused by me not properly checking if the More Difficulties mod was enabled. Bug has existed since v1.2.0, probably.

Fixed in v1.2.3
