### ISSUE TITLE
Missplace or incompatibility with more difficulties

### ISSUE THREAD

**Issue by LumerGD120** [hiimjustin000/FakeRate#2]
Android64  It only does it with 9 stars

No More difficulties 
![Screenshot_2024-04-29-16-17-50-26](https://github.com/hiimjustin000/FakeRate/assets/147040389/8a2bb470-9a85-44df-952c-6745558c17ff)

With More difficulties
![Screenshot_2024-04-29-16-18-30-33](https://github.com/hiimjustin000/FakeRate/assets/147040389/fdea71db-e33b-4807-8923-fd1777606d19)

**Comment by hiimjustin000** [comment]
Fixed in v1.1.2, will be released when accepted on the Geode mod index

**Comment by LumerGD120** [comment]
> Fixed in v1.1.2, will be released when accepted on the Geode mod index

Also it only does do that with coins and cruel 9 stars
