### ISSUE TITLE
[Suggestion] Stat gain settings

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#21]
Suggestion for options for stat gain. Such as orbs and stars (maybe not orbs , it seems hard). Also a customizable limit Stat Gain Guard so you won't gain more than let's say 69 stars if configured to that, even if the level completed is set to 420 stars or something above it or smth else above the (example 69) limit

**Comment by hiimjustin000** [comment]
I actually do not think this is a good idea.
