### ISSUE TITLE
#16 got reintroduced

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#25]
#16 is back So imma revert to an older version until fix

**Comment by hiimjustin000** [comment]
How do you reproduce this? I cannot seem to do this myself.

**Comment by heavyutils** [comment]
> How do you reproduce this? I cannot seem to do this myself.

Like the one before. Rate a level rated 4, 7, or 9 to anything else, boom

**Comment by hiimjustin000** [comment]
Existed since v1.2.7, fixed in v1.2.8
