### ISSUE TITLE
[Bug report] Incompatability with godlike faces.

### ISSUE THREAD

**Issue by polygoners1** [hiimjustin000/FakeRate#26]
If you have godlike faces then legendary and mythical fake rated levels will appear as, well idk.
![Screenshot_20240705-185037_Geode](https://github.com/hiimjustin000/FakeRate/assets/149721398/dd642caa-0410-477e-bd3a-88b97c262265)
![Screenshot_20240705-185045_Geode](https://github.com/hiimjustin000/FakeRate/assets/149721398/33803031-70b8-436c-b8d9-aa45c83b67ef)

**Comment by polygoners1** [comment]
Also globed featured levels dont have to do with this bug.

**Comment by hiimjustin000** [comment]
Looks like an issue with Godlike Faces itself

**Comment by hiimjustin000** [comment]
It's an issue with GodlikeFaces itself. [I forwarded this to Adya](https://github.com/AdyaGMD/GodLikeFaces/pull/5), but I haven't gotten a response yet.

**Comment by polygoners1** [comment]
Huh, i downladed the update but its still hapening.
![Screenshot_20240706-082551_Geode](https://github.com/hiimjustin000/FakeRate/assets/149721398/9e6a87eb-e590-41ad-9afc-b47adcf22818)

**Comment by hiimjustin000** [comment]
Read my comment.
