### ISSUE TITLE
Incompatibility on animated fire mod

### ISSUE THREAD

**Issue by LumerGD120** [hiimjustin000/FakeRate#28]
Here is an exmaple
 https://github.com/user-attachments/assets/b81213ac-3ea6-4965-bf62-cfa5a7caf422

**Comment by LumerGD120** [comment]
Bloudeleuste is fake rate

**Comment by hiimjustin000** [comment]
I encountered this as well. I decided to leave it because I can't really do much other than get Uproxide to fix it. I'll let her know.

**Comment by hiimjustin000** [comment]
Fixed by Uproxide/animated-fire#5, idk when it will update
