### ISSUE TITLE
Suggestion to remove Star limit

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#29]
Pls remove -128 to 127 limit of the stars u can set. It causes no problems of what I've tested out so far (through source edit).

**Comment by Foxiseminger** [comment]
idk that the maximum robtop's servers can handle but gd mod though

**Comment by Foxiseminger** [comment]
hmmmmm

**Comment by hiimjustin000** [comment]
Added in v1.3.3
