### ISSUE TITLE
Grandpa Demon effects are not applied or removed

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#30]
The beautiful effects on the level page don't show up if I make retray grandpa demon. And they don't disappear if I rerate tidal wave to easy.

**Comment by hiimjustin000** [comment]
I will close this issue when I figure out a way to fix this.

**Comment by heavyutils** [comment]
EffectsManager.h might have what you want

I found this line of code. It's also a resource, but from last time I used it, I feel like there's more than just that sprite:

CCSprite::createWithSpriteFrameName("GrD_demon4_infinity.png"_spr);

**Comment by hiimjustin000** [comment]
Fixed in v1.4.0
