### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by lance21312** [hiimjustin000/FakeRate#35]
Log:

2024-08-11T20:05:47-0400
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "hiimjustin000.fake_rate" mod. Please submit this crash report to its developers (hiimjustin000) for assistance.

== Geode Information ==
Loader Version: v3.4.0
Loader Commit: a533b5f
Bindings Commit: de6a02b
Installed mods: 13
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll
Faulty Mod: Fake Rate v1.3.6 (hiimjustin000.fake_rate)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFA95F44E85 (hiimjustin000.fake_rate.dll + 4e85)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + 4e85
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + 3a59
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + a5f6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + 2a8b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + 156b6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 000001E9B5120872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3c0a5 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 000001E9B5120872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 000001E9B5120C72 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3c76f (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 000001E9B5120C72 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + b0c3c (cocos2d::CCTouchDispatcher::touches + 444)
 - 000001E9B5126C72 (Hook handler)
 - 000001E9B5126C72 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76159 (cocos2d::CCEGLView::onGLFWMouseCallBack + 249)
 - 000001E9CF4FE47B (Hook handler)
 - 000001E9CF4FE47B (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76186
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d686b
 - C:\WINDOWS\System32\USER32.dll + 189a1
 - C:\WINDOWS\System32\USER32.dll + 181eb (CallWindowProcW + 139)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 41eb4
 - C:\WINDOWS\System32\USER32.dll + 189a1
 - C:\WINDOWS\System32\USER32.dll + 18461
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d4198
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72ca6 (cocos2d::CCApplication::run + 1078)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2453da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 00007ffaa53916e0
RBX: 0000000000000000
RCX: 0000000000000000
RDX: 0000002bad3ee001
RBP: 0000000000000000
RSP: 0000002bad3efb80
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffade54af28
R8:  000001e9b1d80f00
R9:  0000000000000001
R10: 0000000000000003
R11: 0000002bad3edff0
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.8.3] beat.click-sound
x | [v2.11.0] fleym.nongd
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.1.7] hiimjustin000.demons_in_between
x | [v1.3.6] hiimjustin000.fake_rate
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.0.0-alpha.2] sabe.persistenceapi
x | [v1.0.1-alpha.3] sabe.platformersaves
x | [v1.1.21] syzzi.click_between_frames
x | [v1.5.6] thesillydoggo.qolmod
x | [v1.2.0] weebify.separate_dual_icons

**Comment by hiimjustin000** [comment]
Fixed in v1.3.7
