### ISSUE TITLE
More difficulties stick bug

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#38]
Rerating a rated More Difficulties level (particularly Tough) to a base difficulty (easy,normal,hard,harder,insane) will make the [Casual/Tough/Cruel] face stick on the level page, but on the saved level page it works fine.

**Comment by heavyutils** [comment]
![Screenshot 2024-08-20 070231](https://github.com/user-attachments/assets/8d4eaa23-51e5-4591-b0c5-485993cdf1c5)
![Screenshot 2024-08-20 070207](https://github.com/user-attachments/assets/30e29ed0-30a6-447b-aa15-f103e52705ee)

**Comment by hiimjustin000** [comment]
Fixed in v1.4.5
