### ISSUE TITLE
Always crash

### ISSUE THREAD

**Issue by ItsYaProgramPlayzXDAlt** [hiimjustin000/FakeRate#4]
== Geode Information ==
Loader Version: v2.0.0-beta.25
Loader Commit: 20dc3c9
Bindings Commit: 2eb85b0
Installed mods: 90
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\Together\Desktop\Game\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll
Faulty Mod: hiimjustin000.fake_rate
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 626BE8A2 (hiimjustin000.fake_rate.dll + e8a2)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Users\Together\Desktop\Game\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + e8a2
 - C:\Users\Together\Desktop\Game\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + 11745
 - C:\Users\Together\Desktop\Game\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + fe21
 - C:\Users\Together\Desktop\Game\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + e4eb
 - C:\Users\Together\Desktop\Game\geode\unzipped\hiimjustin000.fake_rate\hiimjustin000.fake_rate.dll + b997

== Register States ==
EAX: 00000000
EBX: 1e2ba208
ECX: 1e2671f8
EDX: 012b0000
EBP: 00f3ee34
ESP: 00f3eda0
EDI: 1e2671f8
ESI: 00f3eda0
EIP: 626be8a2

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.1.3] adam_729.deathmarkers
x | [v1.1.2] adyagd.godlikefaces
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.1] alphalaneous.transparent_lists
x | [v1.0.0] alphalaneous_raydeeux.changefont19
x | [v1.0.2] arkane.dl-team-icons
  | [v1.1.0] artoree.enhanced_menu
x | [v1.8.0] beat.click-sound
x | [v1.0.4] bitz.moregames
x | [v1.0.3] bulletbot.gamemode_changer
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.0.3] capeling.coloured-wave-trail
x | [v1.0.5] capeling.gamemode_picker
  | [v1.0.5] capeling.geometry-dash-lunar
x | [v1.0.0] capeling.usable_explorers
x | [v1.1.4] cdc.more-hints
x | [v1.0.1] cj_link.fakemoderator
x | [v1.0.2] colon.gold_user_coins
x | [v1.3.1] creatorcreepy.unixsync
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.7] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.5.0] egg.icon_hack
x | [v1.0.0] ekv.save_on_level_page
x | [v1.3.1] elnexreal.copy_song_id
x | [v1.3.1] elsai.a_daily_shop
x | [v1.0.2] elsai.pause_menu_zoom
x | [v1.0.4] firee.GoldenBest
  | [v1.6.2] firee.PrismMenu
x | [v2.7.1] fleym.nongd
x | [v1.2.19] gdutilsdevs.gdutils
x | [v1.5.6] geode.custom-keybinds
x | [v2.0.0-beta.25] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.1.1] hiimjustin000.fake_rate
x | [v6.3.3] hjfod.betteredit
x | [v1.0.2] iandyhd3.wsliveeditor
x | [v1.1.0] itzkiba.better_progression
x | [v1.0.2] itzkiba.elegant_rankings
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.2.0] khronophobia.more_settings_button
x | [v1.2.0] khronophobia.shortcuts_menu
x | [v1.3.1] m336.levelinfo
x | [v1.0.3] mat.run-info
x | [v1.1.0] mat.scroll-zoom
x | [v1.0.0-beta.17] minemaker0430.gddp_integration
x | [v1.1.1] mishpro.comments_in_pause_menu
x | [v1.2.0] ml5.treasure-checklist
x | [v2.0.4-beta.1] muhammadgames.bettermenu
x | [v1.2.0] naxrin.garage_in_editor
x | [v1.1.1] ninkaz.blending_glow
x | [v1.2.5] nytelyte.wave_trail_drag_fix
x | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.1.1] petitfrapo.nomoregrayfilter
  | [v1.0.0] polsk.boring_delay_info
x | [v1.0.0] polsk.pause_settings
x | [v2.2.2] prevter.openhack
x | [v1.0.1] relative.advanced_song_search
x | [v1.0.0] relative.scroll_faster_with_ctrl
x | [v0.1.6] rooot.custom-gamemode-colors
x | [v0.0.0-beta.5] ruhax.indecreaseicons
x | [v1.1.0] rynat.better_unlock_info
x | [v1.0.2] slammy333.save_button
x | [v1.1.0] sofabeddd.colored_icon_kit
x | [v1.0.3] sofabeddd.geometry_dash
x | [v1.0.9] syzzi.click_between_frames
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.3.9] TheSillyDoggo.Cheats
x | [v1.0.0-beta.7] thesillydoggo.comment_emojis
x | [v1.0.1] thesillydoggo.dialogue_handler
x | [v2.2.4] TheSillyDoggo.GradientPages
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.2.0] thesillydoggo.moretags
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.1.0] tpdea.sceneswitcher
x | [v1.1.0] tpdea.scroll_any_input
x | [v1.0.0] tpdea.wavetrailglowy
x | [v1.0.3] undefined0.buttoneasing
x | [v1.1.0] uproxide.autosong
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.1.0] uproxide.more_difficulties
x | [v1.2.0] uproxide.quotes
x | [v1.0.0] user95401.window-name
x | [v1.1.3] weebify.coins_in_pause_menu
  | [v1.0.1] weebify.congregation_jumpscare
  | [v1.0.1] weebify.randomizecreatorlayer-geode
x | [v1.1.2] weebify.restartbtn
x | [v1.0.3] weebify.separate_dual_icons

**Comment by hiimjustin000** [comment]
You have the wrong More Difficulties version.

**Comment by ItsYaProgramPlayzXDAlt** [comment]
Its already Latest version.
