### ISSUE TITLE
Game crashes when I click the Fake Rate button.

### ISSUE THREAD

**Issue by wpyxpilot** [hiimjustin000/FakeRate#6]
I do have the more difficulties mod installed, but it is disabled. Do I need to uninstall it?

**Comment by wpyxpilot** [comment]
Nevermind, I uninstalled More Difficulties and it worked.

**Comment by heavyutils** [comment]
Isn't More Difficulties a dependency?

**Comment by hiimjustin000** [comment]
No, earlier versions were marked incompatible, but I misspelled "incompatibilities", leading to this. It was fixed in later versions of Fake Rate, though.

**Comment by heavyutils** [comment]
Why did I have to update More Difficulties to use this mod, then?

**Comment by hiimjustin000** [comment]
Because More Difficulties updated to use a spritesheet instead of individual textures.
