### ISSUE TITLE
WHY ARE MY LEVELS DEMON????

### ISSUE THREAD

**Issue by Foxiseminger** [hiimjustin000/FakeRate#8]
![Screenshot 2024-05-26 224531](https://github.com/hiimjustin000/FakeRate/assets/158284627/84b62c24-b034-420a-b600-35f50db17c3a)

Do I even have to explain this?

**Comment by hiimjustin000** [comment]
You installed my mod [NA Demon](https://geode-sdk.com/mods/hiimjustin000.na_demon).

**Comment by Foxiseminger** [comment]
Oh ok

**Comment by FoxyWorld1** [comment]
oh ok

**Comment by FoxyWorld1** [comment]
got

**Comment by FoxyWorld1** [comment]
also it's 11:00 my time so ummm goodnight
