### ISSUE TITLE
Incompatible with grandpa demon

### ISSUE THREAD

**Issue by CuteistFox** [hiimjustin000/FakeRate#9]
When a fakerate is added on a level with a grandpa demon icon (i did  tidal wave btw) the game crashes

**Comment by hiimjustin000** [comment]
What version

**Comment by hiimjustin000** [comment]
Post the crash log

**Comment by hiimjustin000** [comment]
I accidentally screwed up the compatibility. Fixed in v1.1.7, which will be out in a few minutes.
